name: Deploy to GitHub Pages

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Prepare preview directory
        id: preview
        run: |
          # Replace slashes with dashes in branch name
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            BRANCH_NAME="${{ github.head_ref }}"
          else
            BRANCH_NAME="${GITHUB_REF_NAME}"
          fi
          
          # Replace slashes with dashes for safety
          DEPLOY_PATH="${BRANCH_NAME//\//-}"
          echo "deploy_path=${DEPLOY_PATH}" >> $GITHUB_OUTPUT
          
          # Create preview directory structure
          mkdir -p "preview-out/${DEPLOY_PATH}"
          cp -r dist/* "preview-out/${DEPLOY_PATH}/"
          
          # Copy 404.html to root for routing
          cp dist/404.html preview-out/

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: preview-out
          keep_files: true
          publish_branch: gh-pages

      - name: Find Comment
        uses: peter-evans/find-comment@v3
        if: github.event_name == 'pull_request'
        id: fc
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '🎉 **Preview Deployed!**'

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🎉 **Preview Deployed!**  
            👉 [View Preview](https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ steps.preview.outputs.deploy_path }})
          edit-mode: replace